comun: A community table with samples as rows and taxa as columns. 

net<-function(comun){
     require(Hmisc)
     require(igraph)
     b_to<-rcorr(comun,type="spearman")
     r<-b_to$r
     p<-b_to$P
     r[r<0.6]<-0
     p<-p.adjust(p, method="fdr")
     q<-matrix(p,nrow=ncol(comun),ncol=ncol(comun))
     q[q<0.01]<-1
     q[q>0.01&q<1]<-0
     gg<-r*q
     diag(gg) <- 0
     g <- graph.adjacency(gg, weighted=TRUE, mode="undirected")
     g <- simplify(g)
     return(g)
}

###net: the network generated by function net()
###Caculation of node-level topological features
degree(net)####Degree
betweenness(net)####Betweenness centrality
closeness(net)####Closeness centrality

###Caculation of network-level topological features
length(V(net))###Number of nodes
length(E(net))###Number of edges
length(E(net))/length(V(g))###Average degree
transitivity(net)###Clustering coefficient
average.path.length(net)###Average path length
diameter(net)###Network diameter
graph.density(net)###Graph density
